del *.log
del b1

db.exe "drop table t1"
db.exe "create table t1(num int)"
db.exe "insert into t1 values (1)"
db.exe "insert into t1 values (11)"
db.exe "insert into t1 values (111)"
db.exe "insert into t1 values (1111)"

db.exe "drop table students"
db.exe "create table students(id int not null, first char(12), last char(12), status char(2), gpa int, gender char(1))"
db.exe "insert into students values(1, 'Douglas', 'Belford', 'FM', 2, 'M')"
db.exe "insert into students values(2, 'Joe', 'Leng', NULL, 0, 'M')"
db.exe "insert into students values(3, 'Jason', 'Caceres', 'JR', 3, 'M')"
db.exe "insert into students values(4, 'Eric', 'Toledo', 'SR', 3, 'M')"
db.exe "insert into students values(5, 'Douglas', 'Bottenhorn', NULL, 3, 'M')"
db.exe "insert into students values(6, 'Josh', 'Woolsey', 'SR', 3, 'M')"
db.exe "insert into students values(7, 'Harry', 'Maurer', 'JR', 2, 'M')"
db.exe "insert into students values(8, 'Lin', 'Woolsey', 'FM', 1, 'M')"
db.exe "insert into students values(9, 'Jon', 'Austin', 'SR', 2, 'M')"
db.exe "insert into students values(10, 'Adam', 'Morrissey', NULL, 3, 'M')"
db.exe "insert into students values(11, 'Don', 'Lee', NULL, 3, 'M')"
db.exe "insert into students values(12, 'Joe', 'Roth', NULL, 2, 'M')"
db.exe "insert into students values(13, 'Hosun', 'Miller', 'SF', 3, 'M')"
db.exe "insert into students values(14, 'Ross', 'Alkouh', NULL, NULL, 'M')"
db.exe "insert into students values(15, 'Mark', 'Stribling', 'SF', 3, 'M')"
db.exe "insert into students values(16, 'Ryan', 'Zeleski', 'SR', 2, 'M')"
db.exe "insert into students values(17, 'Matt', 'Lee', 'JR', 0, 'M')"
db.exe "insert into students values(18, 'Matt', 'Lawrence', 'FM', NULL, 'M')"
db.exe "insert into students values(19, 'Hosun', 'Kay', 'JR', 3, 'M')"
db.exe "insert into students values(20, 'Mark', 'Borden', 'FM', 3, 'M')"
db.exe "insert into students values(21, 'Theresa', 'Lee', 'SR', 2, 'F')"
db.exe "insert into students values(22, 'Brian', 'Balzer', NULL, 3, 'M')"
db.exe "insert into students values(23, 'Mike', 'Behrens', 'SR', 1, 'M')"
db.exe "insert into students values(24, 'Cord', 'Kinney', 'FM', 1, 'M')"
db.exe "insert into students values(25, 'Hosun', 'Caceres', 'JR', 1, 'M')"
db.exe "insert into students values(26, 'Colin', 'Shen', 'SR', 1, 'M')"
db.exe "insert into students values(27, 'Vince', 'Chyn', 'JR', 0, 'M')"
db.exe "insert into students values(28, 'Destin', 'Davis', 'SF', 2, 'M')"
db.exe "insert into students values(29, 'William', 'Berger', 'FM', 3, 'M')"
db.exe "insert into students values(30, 'Andy', 'Barr', NULL, 2, 'M')"
db.exe "insert into students values(31, 'Ryan', 'Chyn', 'SR', 3, 'M')"
db.exe "insert into students values(32, 'Colin', 'Lee', 'JR', 2, 'M')"
db.exe "insert into students values(33, 'Colin', 'Choi', NULL, 1, 'M')"
db.exe "insert into students values(34, 'William', 'Anderberg', 'FM', 3, 'M')"
db.exe "insert into students values(35, 'Chris', 'Bales', 'JR', 3, 'M')"
db.exe "insert into students values(36, 'Jesse', 'Behrens', 'SR', 2, 'M')"
db.exe "insert into students values(37, 'Ellisa', 'Simpson', 'SR', 0, 'F')"
db.exe "insert into students values(38, 'Josh', 'Hamilton', NULL, 2, 'M')"
db.exe "insert into students values(39, 'Heather', 'Shen', NULL, 3, 'F')"
db.exe "insert into students values(40, 'Colin', 'Maurer', 'JR', 0, 'M')"
db.exe "insert into students values(41, 'Jeff', 'Bianco', 'SR', 0, 'M')"
db.exe "insert into students values(42, 'Joe', 'Zeleski', 'SR', 2, 'M')"
db.exe "insert into students values(43, 'Homoud', 'Austin', 'SR', 1, 'M')"
db.exe "insert into students values(44, 'Ross', 'Damelio', 'FM', 1, 'M')"
db.exe "insert into students values(45, 'Vince', 'Bucker', 'FM', 3, 'M')"
db.exe "insert into students values(46, 'Hosun', 'Kirchmer', 'JR', 1, 'M')"
db.exe "insert into students values(47, 'Theresa', 'Roth', 'JR', 3, 'F')"
db.exe "insert into students values(48, 'Adam', 'Braz', 'SF', 1, 'M')"
db.exe "insert into students values(49, 'Josh', 'Kay', 'SF', 2, 'M')"
db.exe "insert into students values(50, 'Mellisa', 'Toledo', 'SF', 0, 'F')"
db.exe "insert into students values(51, 'John', 'Sweeney', 'FM', NULL, 'M')"
db.exe "insert into students values(52, 'Nathan', 'Simpson', 'FM', 1, 'M')"
db.exe "insert into students values(53, 'Colin', 'Nakayama', 'SR', 1, 'M')"
db.exe "insert into students values(54, 'Jea', 'Shen', NULL, 0, 'M')"

db.exe "drop table t2"
db.exe "create table t2(num int)"
db.exe "insert into t2 values (2)"
db.exe "insert into t2 values (22)"
db.exe "insert into t2 values (222)"
db.exe "insert into t2 values (2222)"

db.exe "drop table class"
db.exe "create table class(Student_name char(20) not null, Gender char(1), Exams int, Quiz_total int, Total int not null)"
db.exe "insert into class values('Douglas Belford', 'M', 98, 200, 298)"
db.exe "insert into class values('Joe Leng', 'M', 50, 100, 150)"
db.exe "insert into class values('Jason Caceres', 'M', 70, 130, 200)"
db.exe "insert into class values('Eric Toledo', 'M', 80, 120, 200)"
db.exe "insert into class values('Douglas Bottenhorn', 'M', 86, 150, 236)"
db.exe "insert into class values('Theresa Lee','F', 90, 200, 290)"
db.exe "insert into class values('Brian Balzer','M', 70, 200, 270)"
db.exe "insert into class values('Mike Behrens', 'M', 91, 150, 241)"
db.exe "insert into class values('Cord Kinney', 'M', 20, 0, 20)"
db.exe "insert into class values('Hosun Caceres', 'M', 35, 100, 135)"
db.exe "insert into class values('Ellisa Simpson', 'F', 100, 200, 300)"
db.exe "insert into class values('Josh Hamilton','M', 0, 0, 0)"
db.exe "insert into class values('Heather Shen', 'F', 80, 160, 240)"
db.exe "insert into class values('Colin Maurer', 'M', 85, 125, 210)"
db.exe "insert into class values('Mellisa Toledo', 'F', 95, 200, 295)"
